// src/components/Blog/Disqus.vue
<template>
  <div class="row comments pb-3 justify-content-center">
    <div class="col-lg-10 order-lg-2 text-center">
      <div class="mx-auto mt-3">
        <client-only>
          <lazy-component>
            <Disqus :page-config="pageConfig" />
          </lazy-component>
        </client-only>
      </div>
    </div>
  </div>
</template>

<script>
import { DISQUS_SHORTNAME } from '~/utils/config';

export default {
  props: {
    title: {
      type: String,
      required: true
    },
    url: {
      type: String,
      required: true
    },
    identifier: {
      type: String,
      required: true
    }
  },
  computed: {
    pageConfig() {
      return {
        title: this.title,
        url: this.url,
        identifier: `${DISQUS_SHORTNAME}/blog/${this.identifier}`
      };
    }
  }
};
</script>

// src/components/layouts/blog/Disqus.tsx
import { FunctionComponent } from 'react';
import { DiscussionEmbed } from 'disqus-react';
import { DISQUS_SHORTNAME } from '@/utils/config';

interface Props {
  url: string;
  identifier: string;
  title: string;
  locale?: 'en'|'id'|string;
}

const Disqus: FunctionComponent<Props> = (props) => {
  return (
    <div className="container max-w-5xl mt-40 mx-auto">
      <DiscussionEmbed
        shortname={DISQUS_SHORTNAME}
        config={
          {
            ...props,
            language: props.locale === 'id' ? 'id' : undefined
          }
        }
      />
    </div>
  );
};

export default Disqus;
