// components/Base/Footer.vue
<template>
  <footer class="footer has-cards">
    <div class="container">
      <div class="row row-grid align-items-center my-md">
        <div class="col-lg-6">
          <h4 class="mb-0 font-weight-light">
            Let's get in touch on my social.
          </h4>
        </div>
        <div class="col-lg-6 text-lg-center btn-wrapper">
          <a
            v-for="(social, i) in socials"
            :key="i"
            :href="social.link"
            :class="`btn btn-neutral btn-icon-only btn-round btn-lg ${social.class}`"
            :aria-label="social.class.split('-')[1].toUpperCase()"
            target="_blank"
            rel="noopener"
            data-toggle="tooltip"
            data-original-title="Contact me"
          >
            <client-only>
              <component :is="social.icon" />
            </client-only>
          </a>
        </div>
      </div>
      <hr>
      <div class="row align-items-center justify-content-md-between">
        <div class="col-md-6">
          <div class="copyright">
            &copy; {{ new Date().getFullYear() }}
            <a :href="env.site" target="_blank" rel="noopener">{{ env.siteName }}</a>
            &nbsp;•&nbsp;
            <a href="https://github.com/sutanlab/sutanlab.id" target="_blank" rel="noopener">Built</a>
            with <span style="text-decoration: underline dotted">Bullshit</span> by
            <a href="https://github.com/sutanlab" target="_blank" rel="noopener">
              {{ env.author }}
            </a>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

<script>
import LogoOctocatIcon from 'vue-ionicons/dist/logo-octocat.vue'
import LogoLinkedinIcon from 'vue-ionicons/dist/logo-linkedin.vue'
import LogoInstagramIcon from 'vue-ionicons/dist/logo-instagram.vue'
import LogoFacebookIcon from 'vue-ionicons/dist/logo-facebook.vue'
import LogoTwitterIcon from 'vue-ionicons/dist/logo-twitter.vue'
import {
  PRODUCTION_URL,
  SITE_NAME,
  AUTHOR_NAME,
  GITHUB_USERNAME,
  LINKEDIN_USERNAME,
  INSTAGRAM_USERNAME,
  FACEBOOK_USERNAME,
  TWITTER_USERNAME
} from '~/utils/config'

export default {
  components: {
    LogoOctocatIcon,
    LogoLinkedinIcon,
    LogoInstagramIcon,
    LogoFacebookIcon,
    LogoTwitterIcon
  },
  data: () => ({
    env: {
      site: PRODUCTION_URL,
      siteName: SITE_NAME,
      author: AUTHOR_NAME
    },
    socials: [
      { icon: 'logo-octocat-icon', link: `https://github.com/${GITHUB_USERNAME}`, class: 'btn-github' },
      { icon: 'logo-linkedin-icon', link: `https://www.linkedin.com/in/${LINKEDIN_USERNAME}`, class: 'btn-linkedin' },
      { icon: 'logo-instagram-icon', link: `https://www.instagram.com/${INSTAGRAM_USERNAME}`, class: 'btn-instagram' },
      { icon: 'logo-facebook-icon', link: `https://www.facebook.com/${FACEBOOK_USERNAME}`, class: 'btn-facebook' },
      { icon: 'logo-twitter-icon', link: `https://www.twitter.com/${TWITTER_USERNAME}`, class: 'btn-twitter' }
    ]
  })
}
</script>

// src/modules/Common/components/Footer/Footer.tsx
'use client';

import { Facebook, Github, Instagram, Linkedin, Twitter } from 'lucide-react';

import {
  AUTHOR_FACEBOOK,
  AUTHOR_GITHUB,
  AUTHOR_INSTAGRAM,
  AUTHOR_LINKEDIN,
  AUTHOR_NAME,
  AUTHOR_TWITTER
} from '@/configs/author';
import { BASE_URL, SITE_NAME } from '@/configs/sites';
import cn from '@/designs/utils/cn';
import { Link } from '@/packages/components/base/Navigations';

const currentYear = new Date().getFullYear();

const socialLinks = [
  {
    name: 'GitHub',
    href: `https://github.com/${AUTHOR_GITHUB}`,
    icon: Github,
    className: 'bg-[#333]'
  },
  {
    name: 'Twitter',
    href: `https://twitter.com/${AUTHOR_TWITTER}`,
    icon: Twitter,
    className: 'bg-[#1DA1F2]'
  },
  {
    name: 'Instagram',
    href: `https://instagram.com/${AUTHOR_INSTAGRAM}`,
    icon: Instagram,
    className: 'bg-gradient-to-r from-[#f09433] via-[#e6683c] via-[#dc2743] via-[#cc2366] to-[#bc1888]'
  },
  {
    name: 'LinkedIn',
    href: `https://linkedin.com/in/${AUTHOR_LINKEDIN}`,
    icon: Linkedin,
    className: 'bg-[#0077B5]'
  },
  {
    name: 'Facebook',
    href: `https://facebook.com/${AUTHOR_FACEBOOK}`,
    icon: Facebook,
    className: 'bg-[#1877F2]'
  }
];

function Footer() {
  return (
    <footer className="footer-custom w-full h-full">
      <div className="base-container">
        <div className="relative z-10 flex my-16 flex-col justify-between lg:items-center lg:flex-row">
          <p className="text-2xl text-left mx-1">
          Let&lsquo;s get in touch on my social.
          </p>
          <div className="flex gap-x-3 my-4 lg:my-0">
            {socialLinks.map((social) => (
              <Link
                key={social.name}
                href={social.href}
                target="_blank"
                rel="noopener noreferrer"
                className={cn([
                  'p-3 rounded-lg text-white hover:text-white hover:-translate-y-1',
                  social.className
                ])}
                aria-label={social.name}
              >
                <social.icon className="w-4 h-4" />
              </Link>
            ))}
          </div>
        </div>
        <hr className="relative z-10" />
        <div className="relative z-10 my-12 text-sm text-center sm:text-left">
          <span className="inline-block">&copy;&nbsp;{currentYear}&nbsp;</span>
          <Link className="inline-block font-semibold" href={BASE_URL}>{SITE_NAME}</Link>
          <span className="inline-block mx-1">&bull;</span>
          <Link className="inline-block mx-0.5" href={`https://github.com/${AUTHOR_GITHUB}/gading.dev`}>Built</Link>
          <span className="inline-block mx-0.5">with</span>
          <span className="inline-block border-b-2 border-dotted mx-0.5 leading-tight">Bullshit</span>
          <span className="inline-block mx-0.5">by</span>
          <Link className="inline-block text-primary mx-0.5" href={`https://github.com/${AUTHOR_GITHUB}`}>
            {AUTHOR_NAME}
          </Link>
          <div className="text-base-content mt-2">
            <Link className="inline-block text-primary" href="/docs/colors">
              Colors System
            </Link>
            <span className="inline-block mx-1">&bull;</span>
            <Link className="inline-block text-primary" href={`${BASE_URL}/rss/feed.xml`}>
              Feed RSS
            </Link>
            <span className="inline-block mx-1">&bull;</span>
            <Link className="inline-block text-primary" href={`${BASE_URL}/sitemap.xml`}>
              Sitemap
            </Link>
          </div>
        </div>
      </div>
    </footer>
  );
}

export default Footer;
