// src/pages/index.vue
<template>
  <div class="content-page">
    <Banner height="70vh">
      <div class="text-center">
        <SlideLeft :duration="1500" :delay="200">
          <h1 v-if="$store.getters['router/onMountedShow']" class="text-white text-smooth text-shadow">
            <b>{{ author }}</b>
          </h1>
        </SlideLeft>
        <SlideRight :duration="1500" :delay="200">
          <h5 v-if="$store.getters['router/onMountedShow']" class="text-white text-smooth text-shadow">
            <span id="desc-home" />”
          </h5>
        </SlideRight>
      </div>
    </Banner>
    <section class="section section-skew">
      <div class="container">
        <Card class="card-content" shadow no-body>
          <div class="px-4">
            <div class="row justify-content-center">
              <div class="col-lg-3 order-lg-2">
                <div class="card-content-image">
                  <Lazy tag="span">
                    <img data-src="/assets/img/collections/gading-talks.jpeg" class="rounded-circle" :alt="author">
                  </Lazy>
                </div>
              </div>
              <div class="col-lg-4 order-lg-3 text-lg-right align-self-lg-center">
                <div class="card-content-actions py-4 mt-lg-0">
                  <Button
                    tag="a"
                    target="_blank"
                    rel="noreferrer"
                    href="/media/cv.pdf"
                    type="info"
                    size="sm"
                    class="mr-4"
                  >
                    <client-only>
                      <md-briefcase-icon w="14px" h="14px" />
                    </client-only>
                    CV
                  </Button>
                  <Button
                    tag="a"
                    type="primary"
                    class="float-right"
                    size="sm"
                    :href="`mailto:${email}`"
                  >
                    <client-only>
                      <md-mail-icon w="14px" h="14px" />
                    </client-only>
                    Contact
                  </Button>
                </div>
              </div>
              <div class="col-lg-4 order-lg-1">
                <div class="card-content-stats d-flex justify-content-center">
                  <div>
                    <span class="heading">
                      <span>👨🏻‍💻</span>
                    </span>
                    <span class="description">Writer,</span>
                  </div>
                  <div>
                    <span class="heading">
                      <span>🧐</span>
                    </span>
                    <span class="description">Learner,</span>
                  </div>
                  <div>
                    <span class="heading">
                      <span>😴</span>
                    </span>
                    <span class="description">but Slacker</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="text-center mt-5">
              <h3>
                {{ authorFullname }}
              </h3>
              <div class="h6 font-weight-300">
                Gading, Since 1998
              </div>
              <div class="h6 mt-4">
                Software Engineer, Frontend
              </div>
              <div>
                ORAMI by SIRCLO Group
              </div>
            </div>
            <div class="mt-5 py-4 border-top text-center">
              <div class="row justify-content-center">
                <div class="col-lg-9">
                  <h2 class="text-smooth">
                    About
                  </h2>
                  <p>
                    <client-only>
                      <md-quote-icon w="14px" h="14px" />
                    </client-only>
                    Software Engineer who specialized in frontend side, but have
                    an ability to code in backend side too. Very passionate about
                    modern mobile and web technology using JavaScript while taking into
                    consideration the latest trends and techniques.
                  </p>
                </div>
              </div>

              <div class="row justify-content-center mt-5">
                <div class="col-lg-9">
                  <h2 class="text-smooth">
                    Support Me
                  </h2>
                  <p>
                    Do you like this website? Or do you like some stuff that I've made? <br>
                    You can support me by clicking on one of the buttons below.
                  </p>
                  <Support />
                </div>
              </div>
            </div>
          </div>
        </Card>
      </div>
    </section>
  </div>
</template>

<script>
import { SlideXLeftTransition as SlideLeft, SlideXRightTransition as SlideRight } from 'vue2-transitions';
import MdBriefcaseIcon from 'vue-ionicons/dist/md-briefcase.vue';
import MdMailIcon from 'vue-ionicons/dist/md-mail.vue';
import MdQuoteIcon from 'vue-ionicons/dist/md-quote.vue';
import Card from '~/components/Argon/Card';
import Button from '~/components/Argon/Button';
import Banner from '~/components/Base/Banner';
import Lazy from '~/components/Base/Lazy';
import Support from '~/components/Base/Support';
import MountedAnimation from '~/mixins/mounted-animation';
import { metaGenerator } from '~/utils/helpers';
import { AUTHOR_NAME, AUTHOR_FULLNAME, EMAIL } from '~/utils/config';
import { type } from '~/utils/typical';

export default {
  components: {
    SlideLeft,
    SlideRight,
    Banner,
    Card,
    Button,
    MdMailIcon,
    MdQuoteIcon,
    Lazy,
    MdBriefcaseIcon,
    Support
  },
  mixins: [MountedAnimation],
  data: () => ({
    author: AUTHOR_NAME,
    authorFullname: AUTHOR_FULLNAME,
    email: EMAIL
  }),
  head: () => ({
    title: `${AUTHOR_FULLNAME} | ${AUTHOR_NAME}`,
    meta: metaGenerator('website', {
      title: 'Personal Homepage',
      description: `A Man who turns a cup of coffee into beautiful codes. - ${AUTHOR_NAME}`,
      keywords: 'homepage, portfolio',
      image: '/assets/img/collections/default-banners/1.jpg',
      url: '/'
    })
  }),
  mounted() {
    setTimeout(() => {
      const desc = document.getElementById('desc-home');
      type(desc, 'Just an ordinary Man who turns a cup of coffee into beautiful codes.');
    }, 250);
  }
};
</script>

// src/pages/index.tsx
import { NextPage } from 'next';
import { Fragment } from 'react';
import { Content, Footer, Navbar, Banner, CardHero, Image, withLayoutPage, Button, Icon } from '@/components';
import { AUTHOR_NAME, BASE_URL, SITE_NAME } from '@/utils/config';
import { motion } from 'framer-motion';

import iconMail from '@/assets/icons/tools/ios/mail.svg';
import iconBriefcase from '@/assets/icons/tools/ios/briefcase.svg';

import imgProfile from '@/assets/images/authors/gading-talks.jpeg';

const LeftDesc = ({ className = 'hidden md:flex' }) => (
  <div className={`${className} items-center h-[30px] flex-1 justify-center text-center`}>
    <div className="opacity-90">
      <div>👨🏻‍💻</div>
      <p className="text-light-20 dark:text-light-20">Writer,</p>
    </div>
    <div className="mx-24">
      <div>🧐</div>
      <p className="text-light-20 dark:text-light-20">Explorer,</p>
    </div>
    <div>
      <div>😴</div>
      <p className="text-light-20 dark:text-light-20">Slacker</p>
    </div>
  </div>
);

const RightDesc = ({ className = 'hidden md:flex' }) => (
  <div className={`${className} items-center h-[30px] flex-1 justify-center`}>
    <Button
      href="mailto:contact@gading.dev"
      className="flex items-center text-sm rounded-4 px-8 py-4 text-white dark:text-white bg-primary mx-8 hover:no-underline"
    >
      <Icon size={16} className="mr-4" color="white" src={iconMail} /> Contact
    </Button>
    <Button
      href={`${BASE_URL}/media/cv.pdf`}
      className="flex items-center text-sm rounded-4 px-8 py-4 text-white dark:text-white bg-info mx-8 hover:no-underline"
    >
      <Icon size={14} className="mr-4" color="white" src={iconBriefcase} /> Resume
    </Button>
  </div>
);

const HomePage: NextPage = () => {
  return (
    <Fragment>
      <Navbar />
      <Banner bgImage="/media/banners/1.jpg" className="font-courgette text-white util--text-shadow text-center">
        <div className="container -mt-48">
          <motion.h1
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ ease: 'easeInOut', duration: 0.5 }}
            className="font-bold text-4xl mb-8 text-white dark:text-white"
          >
            {SITE_NAME}
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 25 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ ease: 'easeInOut', duration: 0.5, delay: 0.2 }}
            className="text-lg px-8 text-white dark:text-white"
          >
            My work, my blog, even about my life are all here.”
          </motion.p>
        </div>
      </Banner>
      <Content>
        <CardHero>
          <div className="relative flex justify-around items-start mb-24 md:mb-32 md:-mx-36">
            <LeftDesc />
            <motion.div
              className="-mt-100 w-[180px] h-[180px] flex flex-1 items-center justify-center"
              initial={{ opacity: 0, y: -25 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ ease: 'easeInOut', duration: 0.5, delay: 0.5 }}
            >
              <Image
                classNameWrapper="absolute rounded-full mx-auto shadow-all transition-all hover:-mt-12 mx-auto"
                src={imgProfile}
                alt={AUTHOR_NAME}
                width={180}
                height={180}
                placeholder="blur"
                layout="responsive"
              />
            </motion.div>
            <RightDesc />
          </div>
          <div>
            <div className="mb-32 md:hidden sm:-mt-68">
              <RightDesc className="flex h-[auto] justify-around sm:justify-between sm:px-32 mb-32" />
              <LeftDesc className="flex h-[auto]" />
            </div>
            <div className="max-w-[48rem] mx-auto">
              <h3 className="text-center">
                Sutan Gading Fadhillah Nasution
              </h3>
              <hr className="my-24" />
              <p className="text-center mb-16">
                Hello, I&apos;m <i>Gading</i>. Software Engineer who specialized in Frontend on Full-time work, and also has some ability to code in Backend on Freelance/Side work. Very passionate about modern mobile and web technology while taking into consideration the latest trends and techniques. I would be a fast learner in doing new things and building good teamwork either.
              </p>
              <p className="text-center">
                I would be a fast learner in doing new things and building good teamwork either. Also, made several side or open-source projects on GitHub for fun, and maybe be useful for people who have used it.
              </p>
            </div>
          </div>
        </CardHero>
      </Content>
      <Footer />
    </Fragment>
  );
};

export default withLayoutPage(HomePage, {
  title: 'Gading\'s Hideout'
});
