// src/components/layouts/main/Footer.tsx
import { FunctionComponent } from 'react';
import { Link, Button, Icon } from '@/components/base';
import {
  AUTHOR_NAME,
  FACEBOOK_USERNAME,
  GITHUB_USERNAME,
  INSTAGRAM_USERNAME,
  LINKEDIN_USERNAME,
  BASE_URL,
  SITE_NAME,
  TWITTER_USERNAME
} from '@/utils/config';
import clsxm from '@/utils/helpers/clsxm';
import styles from './styles.module.css';

import iconGithub from '@/assets/icons/logo/octocat.svg';
import iconLinkedin from '@/assets/icons/logo/linkedin.svg';
import iconInstagram from '@/assets/icons/logo/instagram.svg';
import iconFacebook from '@/assets/icons/logo/facebook.svg';
import iconTwitter from '@/assets/icons/logo/twitter.svg';

export interface Props {
  className?: string;
}

const socialLinks = [
  {
    color: 'bg-github',
    logo: iconGithub,
    url: `https://github.com/${GITHUB_USERNAME}`
  },
  {
    color: 'bg-linkedin',
    logo: iconLinkedin,
    url: `https://linkedin.com/in/${LINKEDIN_USERNAME}`
  },
  {
    color: 'bg-instagram',
    logo: iconInstagram,
    url: `https://instagram.com/${INSTAGRAM_USERNAME}`
  },
  {
    color: 'bg-facebook',
    logo: iconFacebook,
    url: `https://facebook.com/${FACEBOOK_USERNAME}`
  },
  {
    color: 'bg-twitter',
    logo: iconTwitter,
    url: `https://twitter.com/${TWITTER_USERNAME}`
  }
];

const Footer: FunctionComponent<Props> = (props) => {
  const { className } = props;
  return (
    <footer className={clsxm('w-full h-full', className, styles.footer)}>
      <div className="flex container mx-auto my-64 flex-col justify-between lg:max-w-5xl lg:flex-row">
        <p className="text-2xl text-left">
          Let&lsquo;s get in touch on my social.
        </p>
        <div className="flex items-center relative h-full my-24 lg:my-0">
          {socialLinks.map((socialLink) => (
            <Button
              key={socialLink.url}
              href={socialLink.url}
              className={`${socialLink.color} shadow-all rounded-8 px-[11px] py-[6px] mx-4 hover:-mt-8`}
            >
              <Icon color="white" size={14} src={socialLink.logo} className="-mt-4" />
            </Button>
          ))}
        </div>
      </div>
      <hr className="container lg:max-w-5xl" />
      <div className="container w-full mx-auto my-48 text-sm max-w-5xl">
        <span className="inline-block">&copy;&nbsp;{new Date().getFullYear()}&nbsp;</span>
        <Link className="inline-block" href={BASE_URL}>{SITE_NAME}</Link>
        <span className="inline-block">&nbsp;&bull;&nbsp;</span>
        <Link className="inline-block" href={`https://github.com/${GITHUB_USERNAME}/gading.dev`}>Built</Link>
        <span className="inline-block">&nbsp;with&nbsp;</span>
        <span className="inline-block util--underline-dotted">Bullshit</span>
        <span className="inline-block">&nbsp;by&nbsp;</span>
        <Link className="inline-block text-primary" href={`https://github.com/${GITHUB_USERNAME}`}>
          {AUTHOR_NAME}
        </Link>
        <div className="-ml-4 dark:text-white">
          <span className="inline-block">&nbsp;See colors system&nbsp;</span>
          <Link className="inline-block text-primary" href="/docs/colors">
            here.
          </Link>
        </div>
      </div>
    </footer>
  );
};

Footer.defaultProps = {
  className: ''
};

export default Footer;

// components/Base/Footer.vue
<template>
  <footer class="footer has-cards">
    <div class="container">
      <div class="row row-grid align-items-center my-md">
        <div class="col-lg-6">
          <h4 class="mb-0 font-weight-light">
            Let's get in touch on my social.
          </h4>
        </div>
        <div class="col-lg-6 text-lg-center btn-wrapper">
          <a
            v-for="(social, i) in socials"
            :key="i"
            :href="social.link"
            :class="`btn btn-neutral btn-icon-only btn-round btn-lg ${social.class}`"
            :aria-label="social.class.split('-')[1].toUpperCase()"
            target="_blank"
            rel="noopener"
            data-toggle="tooltip"
            data-original-title="Contact me"
          >
            <client-only>
              <component :is="social.icon" />
            </client-only>
          </a>
        </div>
      </div>
      <hr>
      <div class="row align-items-center justify-content-md-between">
        <div class="col-md-6">
          <div class="copyright">
            &copy; {{ new Date().getFullYear() }}
            <a :href="env.site" target="_blank" rel="noopener">{{ env.siteName }}</a>
            &nbsp;•&nbsp;
            <a href="https://github.com/sutanlab/sutanlab.id" target="_blank" rel="noopener">Built</a>
            with <span style="text-decoration: underline dotted">Bullshit</span> by
            <a href="https://github.com/sutanlab" target="_blank" rel="noopener">
              {{ env.author }}
            </a>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

<script>
import LogoOctocatIcon from 'vue-ionicons/dist/logo-octocat.vue'
import LogoLinkedinIcon from 'vue-ionicons/dist/logo-linkedin.vue'
import LogoInstagramIcon from 'vue-ionicons/dist/logo-instagram.vue'
import LogoFacebookIcon from 'vue-ionicons/dist/logo-facebook.vue'
import LogoTwitterIcon from 'vue-ionicons/dist/logo-twitter.vue'
import {
  PRODUCTION_URL,
  SITE_NAME,
  AUTHOR_NAME,
  GITHUB_USERNAME,
  LINKEDIN_USERNAME,
  INSTAGRAM_USERNAME,
  FACEBOOK_USERNAME,
  TWITTER_USERNAME
} from '~/utils/config'

export default {
  components: {
    LogoOctocatIcon,
    LogoLinkedinIcon,
    LogoInstagramIcon,
    LogoFacebookIcon,
    LogoTwitterIcon
  },
  data: () => ({
    env: {
      site: PRODUCTION_URL,
      siteName: SITE_NAME,
      author: AUTHOR_NAME
    },
    socials: [
      { icon: 'logo-octocat-icon', link: `https://github.com/${GITHUB_USERNAME}`, class: 'btn-github' },
      { icon: 'logo-linkedin-icon', link: `https://www.linkedin.com/in/${LINKEDIN_USERNAME}`, class: 'btn-linkedin' },
      { icon: 'logo-instagram-icon', link: `https://www.instagram.com/${INSTAGRAM_USERNAME}`, class: 'btn-instagram' },
      { icon: 'logo-facebook-icon', link: `https://www.facebook.com/${FACEBOOK_USERNAME}`, class: 'btn-facebook' },
      { icon: 'logo-twitter-icon', link: `https://www.twitter.com/${TWITTER_USERNAME}`, class: 'btn-twitter' }
    ]
  })
}
</script>
